all:
  hosts:
    node1:
      ansible_host: 10.30.1.220
      ip: 10.30.1.220
      access_ip: 10.30.1.220
    node2:
      ansible_host: 10.30.1.221
      ip: 10.30.1.221
      access_ip: 10.30.1.221
    node3:
      ansible_host: 10.30.1.222
      ip: 10.30.1.222
      access_ip: 10.30.1.222
    node4:
      ansible_host: 10.30.1.223
      ip: 10.30.1.223
      access_ip: 10.30.1.223
    node5:
      ansible_host: 10.30.1.224
      ip: 10.30.1.224
      access_ip: 10.30.1.224
    node6:
      ansible_host: 10.30.1.227
      ip: 10.30.1.227
      access_ip: 10.30.1.227
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
